# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-15 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('done', models.CharField(default=0, max_length=1)),
                ('position', models.CharField(max_length=4)),
            ],
        ),
    ]
